export enum CivicStatusEnum {
    INDUCCION          = 'INDUCCION',
    DIAGNOSTICO        = 'DIAGNOSTICO',
    PLANEACION         = 'PLANEACION',
    EN_SEGUIMIENTO     = 'EN_SEGUIMIENTO',
    GRADUADO           = 'GRADUADO',
    // BAJA_POR_INCIDENCIA = 'BAJA_POR_INCIDENCIA',
    BAJA_POR_ACUMULACION_DE_INCIDENCIAS = 'BAJA_POR_ACUMULACION_DE_INCIDENCIAS',
    BAJA_VOLUNTARIA    = 'BAJA_VOLUNTARIA',
    HISTORICO          = 'HISTORICO',
  }
  
  export enum FormStatusEnum {
    PENDIENTE  = 'PENDIENTE',
    EN_PROCESO = 'EN_PROCESO',
    COMPLETADO = 'COMPLETADO',
    CERRADO    = 'CERRADO',
  }

  
  export enum IncidenciaTipoEnum {
    FALTA_INJUSTIFICADA       = 'FALTA_INJUSTIFICADA',
    RETARDO                   = 'RETARDO',
    CONDUCTA_INAPROPIADA      = 'CONDUCTA_INAPROPIADA',
    INCUMPLIMIENTO_TAREA      = 'INCUMPLIMIENTO_TAREA',
    INASISTENCIA_JUSTIFICADA  = 'INASISTENCIA_JUSTIFICADA',
    VISITA_DOMICILIARIA       = 'VISITA_DOMICILIARIA',
    RETIRO_ANTICIPADO         = 'RETIRO_ANTICIPADO',
    CONVERSATORIO             = 'CONVERSATORIO',
  }
  
  export enum IncidenciaEstatusEnum {
    PENDIENTE      = 'PENDIENTE',
    RESUELTA       = 'RESUELTA',
    DERIVO_EN_BAJA = 'DERIVO_EN_BAJA',
  }
  export enum AsistenciaEnum {
    PRESENTE           = 'PRESENTE',
    FALTA_JUSTIFICADA  = 'FALTA_JUSTIFICADA',
    FALTA_INJUSTIFICADA = 'FALTA_INJUSTIFICADA',
    PRESENTE_PARCIAL   = 'PRESENTE_PARCIAL',
  }
  
  
  export enum TipoDocumentoEnum {
    OFICIO_CANALIZACION       = 'OFICIO_CANALIZACION',
    OFICIO_INCORPORACION      = 'OFICIO_INCORPORACION',
    OFICIO_CONCLUSION         = 'OFICIO_CONCLUSION',
    INFORME_INCIDENCIAS       = 'INFORME_INCIDENCIAS',
    OFICIO_BAJA_DEFINITIVA    = 'OFICIO_BAJA_DEFINITIVA',
    OFICIO_MODIFICACION_DIAS  = 'OFICIO_MODIFICACION_DIAS',
    F3_PLAN_TRABAJO           = 'F3_PLAN_TRABAJO',
    F4_CEDULA_INICIAL         = 'F4_CEDULA_INICIAL',
    LISTA_ASISTENCIA          = 'LISTA_ASISTENCIA',
    REPORTE_SEMANAL_GUIA      = 'REPORTE_SEMANAL_GUIA',
    // Nuevos tipos añadidos para documentos generados por el módulo de PDFs
    HOJA_PRESENTACION         = 'HOJA_PRESENTACION',
    PLAN_VIDA                 = 'PLAN_VIDA',
    NOTA_EVOLUCION_PSICOLOGICA = 'NOTA_EVOLUCION_PSICOLOGICA',
  }
  